site_name: Polestar Chip Docs
theme:
  name: readthedocs

# ğŸ‘‡ è¿™ä¸€æ®µéå¸¸é‡è¦ï¼Œå¿…é¡»è¦æœ‰ï¼
plugins:
  - search
  - with-pdf:
      author: Sukiwei
      copyright: Polestar Chip
      output_path: datasheet.pdf