site_name: Polestar Chip Docs

# ğŸ‘‡ å…³é”®å˜åŒ–ï¼šæŠŠä¸»é¢˜æ¢æˆäº† material
theme:
  name: material
  language: zh  # è®©ç•Œé¢å˜æˆä¸­æ–‡

plugins:
  - search
  - with-pdf:
      author: Sukiwei
      copyright: Polestar Chip
      output_path: datasheet.pdf